
backend:
  name: github
  repo: <your-github-username>/<your-fuwari-repo>
  branch: main

media_folder: "src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "blog"
    label: "Bài viết"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "published", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Updated", name: "updated", widget: "datetime", required: false, format: "YYYY-MM-DD" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string", default: "hopthurac" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Lang", name: "lang", widget: "string", default: "vi" }
      - { label: "Canonical URL", name: "canonical", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
